import React from 'react';
import AppLayout from './components/Layout/AppLayout';
import ChatInterface from './components/Tuner/ChatInterface';
import PromptPreview from './components/Editor/PromptPreview';
import { usePromptTemplate } from './hooks/usePromptTemplate';

function App() {
    return (
        <AppLayout>
            <DashboardContent />
        </AppLayout>
    );
}

const DashboardContent = ({ activeMode }) => {
    const { variables, processedPrompt, updateVariable, loadTemplate } = usePromptTemplate(activeMode);
    const [activeTab, setActiveTab] = React.useState('chat'); // 'chat' or 'editor'

    return (
        <div className="flex flex-col h-full gap-4">
            {/* Mobile Tab Switcher */}
            <div className="flex lg:hidden bg-surface/50 p-1 rounded-xl border border-white/10 shrink-0">
                <button
                    onClick={() => setActiveTab('chat')}
                    className={`flex-1 py-2 text-sm font-medium rounded-lg transition-all ${activeTab === 'chat'
                            ? 'bg-primary text-white shadow-lg'
                            : 'text-slate-400 hover:text-white'
                        }`}
                >
                    AI Tuner
                </button>
                <button
                    onClick={() => setActiveTab('editor')}
                    className={`flex-1 py-2 text-sm font-medium rounded-lg transition-all ${activeTab === 'editor'
                            ? 'bg-violet-600 text-white shadow-lg'
                            : 'text-slate-400 hover:text-white'
                        }`}
                >
                    Prompt Editor
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1 min-h-0 overflow-hidden">
                {/* Left: Chat / Tuner Area */}
                <div className={`glass-panel rounded-2xl flex flex-col h-full overflow-hidden ${activeTab === 'chat' ? 'block' : 'hidden lg:flex'
                    }`}>
                    <div className="p-4 border-b border-white/10 bg-white/5 shrink-0">
                        <h3 className="text-lg font-semibold text-blue-300 flex items-center gap-2">
                            AI Tuner
                            <span className="text-xs font-normal text-slate-400 bg-white/5 px-2 py-0.5 rounded-full">Beta</span>
                        </h3>
                    </div>
                    <div className="flex-1 overflow-hidden">
                        <ChatInterface
                            activeMode={activeMode}
                            onApplyPrompt={(prompt) => {
                                updateVariable('prompt', prompt);
                                loadTemplate({
                                    name: 'AI Generated',
                                    description: 'Generated by AI Tuner',
                                    template: prompt,
                                    variables: {}
                                });
                                // モバイルの場合はエディタータブに切り替え
                                if (window.innerWidth < 1024) {
                                    setActiveTab('editor');
                                }
                            }}
                        />
                    </div>
                </div>

                {/* Right: Editor / Preview Area */}
                <div className={`glass-panel rounded-2xl flex flex-col h-full overflow-hidden ${activeTab === 'editor' ? 'block' : 'hidden lg:flex'
                    }`}>
                    <div className="p-4 border-b border-white/10 bg-white/5 shrink-0">
                        <h3 className="text-lg font-semibold text-violet-300">Prompt Editor</h3>
                    </div>
                    <div className="flex-1 overflow-hidden p-4">
                        <PromptPreview
                            promptText={processedPrompt}
                            variables={variables}
                            onUpdateVariable={updateVariable}
                            activeMode={activeMode}
                        />
                    </div>
                </div>
            </div>
        </div>
    );
};

export default App;
